### ISSUE TITLE
List this in janet-lang/pkgs ?

### ISSUE THREAD

**Issue by uvtc** [swlkr/janet-html#4]
This package is missing from [janet-lang/pkgs](https://github.com/janet-lang/pkgs). Could you please add it there? Otherwise, please let me know if you'd like me to create a PR there to add this package.

**Comment by pepe** [comment]
You can PR pkgs with change to pkgs.janet file. I am by the sea, so my reaction time could be longer tho 😉

**Comment by uvtc** [comment]
@swlkr , ok if I add this to the Janet pkgs repo?

**Comment by swlkr** [comment]
@uvtc sounds good to me!

**Comment by uvtc** [comment]
It's in now. https://github.com/janet-lang/pkgs/pull/46 . Closing this.
